create table FOO_Themes (
	uuid_ VARCHAR(75) null,
	colorsId LONG not null primary key,
	neutralBlack VARCHAR(75) null,
	neutralWhite VARCHAR(75) null,
	neutralGray1 VARCHAR(75) null,
	primaryBg VARCHAR(75) null,
	primaryLight VARCHAR(75) null,
	primaryDark VARCHAR(75) null,
	primaryDefault VARCHAR(75) null,
	primaryDisabled VARCHAR(75) null,
	secondaryBg VARCHAR(75) null,
	secondaryLight VARCHAR(75) null,
	secondaryDark VARCHAR(75) null,
	secondaryDefault VARCHAR(75) null,
	secondaryDisabled VARCHAR(75) null,
	successBg VARCHAR(75) null,
	successLight VARCHAR(75) null,
	successDark VARCHAR(75) null,
	successDefault VARCHAR(75) null,
	successDisabled VARCHAR(75) null,
	errorBg VARCHAR(75) null,
	errorLight VARCHAR(75) null,
	errorDark VARCHAR(75) null,
	errorDefault VARCHAR(75) null,
	errorDisabled VARCHAR(75) null,
	warningBg VARCHAR(75) null,
	warningLight VARCHAR(75) null,
	warningDark VARCHAR(75) null,
	warningDefault VARCHAR(75) null,
	warningDisabled VARCHAR(75) null
);

create table THEMES_Themes (
	uuid_ VARCHAR(75) null,
	colorsId LONG not null primary key,
	userId LONG,
	neutralBlack VARCHAR(75) null,
	neutralWhite VARCHAR(75) null,
	neutralGray1 VARCHAR(75) null,
	primaryBg VARCHAR(75) null,
	primaryLight VARCHAR(75) null,
	primaryDark VARCHAR(75) null,
	primaryDefault VARCHAR(75) null,
	primaryDisabled VARCHAR(75) null,
	secondaryBg VARCHAR(75) null,
	secondaryLight VARCHAR(75) null,
	secondaryDark VARCHAR(75) null,
	secondaryDefault VARCHAR(75) null,
	secondaryDisabled VARCHAR(75) null,
	successBg VARCHAR(75) null,
	successLight VARCHAR(75) null,
	successDark VARCHAR(75) null,
	successDefault VARCHAR(75) null,
	successDisabled VARCHAR(75) null,
	errorBg VARCHAR(75) null,
	errorLight VARCHAR(75) null,
	errorDark VARCHAR(75) null,
	errorDefault VARCHAR(75) null,
	errorDisabled VARCHAR(75) null,
	warningBg VARCHAR(75) null,
	warningLight VARCHAR(75) null,
	warningDark VARCHAR(75) null,
	warningDefault VARCHAR(75) null,
	warningDisabled VARCHAR(75) null
);